log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : DEBUG #WARN
      trace     : 'false'
      outputters :
      - datefile
      - console
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
      - console

  # define all outputters (incl. formatters)
  outputters:
  - type     : StderrOutputter
    name     : console
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter

  - type: DateFileOutputter
    name: datefile
    filename: "log/log4r.log" # notice the file extension is needed!
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter